### ISSUE TITLE
Save as eBook removed from Firefox store

### ISSUE THREAD

**Issue by smaragdus** [alexadam/save-as-ebook#35] opened 2020-01-17 03:38 UTC
Hello,

Do you know that [Save as eBook](https://github.com/alexadam/save-as-ebook) was removed from [Firefox Add-ons](https://addons.mozilla.org/en-US/firefox/addon/saveasebook/). If you are aware of that do you know why Mozilla removed your extension from its store?

Regards

**Comment by alexadam** [comment] 2020-01-17 08:43
Hi, I wasn't aware of that... thanks for letting me know. It's my fault, they sent me an email last week but somehow I missed it. Anyway, I uploaded a new version and I hope the problem is fixed now.
Thank you.

**Closed** 2020-01-17 09:08 UTC
Labels: other

**Comment by smaragdus** [comment] 2020-01-17 15:29
@alexadam 

Yes, **Save as eBook** is again available at [Firefox add-ons](https://addons.mozilla.org/en-US/firefox/addon/saveasebook/). However I notice that the Firefox version is **1.3.6**, while Chrome version is still **1.3.5**. Was **Save as eBook** also updated for [Chrome Web Store](https://chrome.google.com/webstore/detail/save-as-ebook/haaplkpoiimngbppjihnegfmpejdnffj)?

Regadrs

**Comment by alexadam** [comment] 2020-01-17 15:43
1.3.6 is just on firefox but there are no changes in the code. I must increment the version nr when uploading a new version and I had to upload a new version to provide some info about the 3rd party libs included

**Comment by smaragdus** [comment] 2020-01-17 15:53
@alexadam 

Thank you for the information.
